
dataset:
  name: mnist 
  path: D:\datasets
  batch_size: 128 
model: 
  name: dac_mnist
  cuda: True 
training:
  epoches: 20 
  upper_threshold: 0.95
  optimizer: 
    name: rmsprop 
    lr: 0.001
